### ISSUE TITLE
部分机型没用

### ISSUE THREAD

**Issue by thsai** [yescpu/KeyboardChangeListener#5]
部分机型没用

**Comment by xingstarx** [comment]
不是部分机型没用吧，主要是对于full screen模式下，这种方案没有用，可以考虑看这个https://zhihu.com/question/44269936/answer/193946701

**Comment by thsai** [comment]
也不是full screen模式吧  我后来发现 是对某些底部有导航栏的手机没用  所以在代码里面判断高度的时候要考虑减掉底部导航栏的高度

**Comment by yescpu** [comment]
已修复
